package com.umuzi.SpringJpa;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

import java.util.Optional;

@Controller // This means that this class is a Controller
@RequestMapping(path="/umuzi") // This means URL's start with /SpringJpa (after Application path)
public class MainController {
    @Autowired // This means to get the bean called customerRepository
    // Which is auto-generated by Spring, we will use it to handle the data
//    private CustomersRepository customersRepository;
    private EmployeesRepository employeesRepository;

//    @GetMapping(path="/all")
//    public @ResponseBody Iterable<Customers> getAllCustomers() {
//        // This returns a JSON or XML with the users
//        return customersRepository.findAll();
//    }
    @GetMapping(path="/all")
    public @ResponseBody Iterable<Employees> getAllEmployees() {
        // This returns a JSON or XML with the users
        return employeesRepository.findAll();
    }
}
